name: pitchboxadmin
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  google_fonts: ^4.0.3
  bottom_navy_bar: ^6.0.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  provider: ^6.0.5
  cloud_firestore: ^4.4.5
  shared_preferences: ^2.0.18
  rounded_loading_button: ^2.1.0
  connectivity_plus: ^3.0.3
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  form_field_validator: ^1.1.0
  im_stepper: ^1.0.1+1
  flutter_form_builder: ^7.5.0
  fluttertoast: ^8.2.1
  image_picker: ^0.8.7+1
  firebase_storage: ^11.1.0
  flutter_statusbarcolor_ns: ^0.5.0
  path: ^1.8.0
  multi_select_flutter: ^4.1.3
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/


